AllCops:
  Exclude:
      - 'db/schema.rb'
      - 'node_modules/**/*'
      - 'bin/*'

Metrics/LineLength:
  Max: 199

Style/BlockComments:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/StringLiterals:
  Enabled: false
