version: '3.4'
services:
  postgres:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  hubzone-webmap:
    build:
      context: .
      cache_from:
      - hubzone/hubzone-webmap:latest
      target: webmap
    image: hubzone/hubzone-webmap:latest
    restart: "no"
    links:
      - postgres
    environment:
    - RAILS_ENV=developmentdocker
    env_file:
    # Create this env file with HUBZONE_GOOGLE_API_KEY populated
    - docker/hubzone-webmap.env
    command: >
      /bin/bash -c "
        function waitfor() {
          while ! nc -z $$1 $$2;
          do
            echo waiting for $$1;
            sleep 3;
          done;
          echo Connected to $$1!;
        }

        waitfor postgres 5432;

        start-rails.sh;
        echo rails process exited, stopping container.;
      "

  hubzone-webmap-nginx:
    build:
      context: .
      cache_from:
      - hubzone/hubzone-webmap:latest
      - hubzone/hubzone-webmap-nginx:latest
      target: nginx
    links:
      - hubzone-webmap
    image: hubzone/hubzone-webmap-nginx:latest
    restart: "no"
    ports:
      - '3000:80'
