version: '3.4'
services:
  postgres:
    image: postgis/postgis:12-master
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rspec:
    build:
      context: ..
      cache_from:
      - hubzone/hubzone-webmap:latest
    image: hubzone/hubzone-webmap:latest
    links:
      - postgres
    entrypoint: ["/bin/bash"]
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=test
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      - HUBZONE_GOOGLE_API_KEY='AIzaSyBsR78bM2H5vMlO60MAtaL9FVtPGWGyQ7c' # Doug's
      - HUBZONE_MAP_DB_USER=postgres
      - HUBZONE_MAP_DB_PASSWORD=postgres
      - HUBZONE_MAP_DB_HOST=postgres
      - HUBZONE_MAP_HOST=local
      #- HUBZONE_API_KEY='AIzaSyBsR78bM2H5vMlO60MAtaL9FVtPGWGyQ7c' # Doug's
    command: >
      -c "
        wget https://s3.amazonaws.com/sba-shared-services-lower-ci/public-files/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
        tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
        rm phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
        mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /bin && \
        rm -r phantomjs-2.1.1-linux-x86_64
        while ! nc -z postgres 5432;
        do
          echo waiting for postgres;
          sleep 1;
        done;
        echo Connected to postgres!;
        bundle exec rake db:create db:migrate &&
        bundle exec rspec spec;
      "
