version: '3.4'
services:
  postgres:
    image: mdillon/postgis:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  rspec:
    build:
      context: ..
      target: webmap-test
      cache_from:
      - hubzone/hubzone-webmap:latest
      - hubzone/webmap-chrometest:latest
    image: hubzone/webmap-chrometest:latest
    shm_size: 2G
    environment:
    - CHROMEDRIVER_WHITELISTED_IPS=""
    links:
      - postgres
    env_file:
      - hubzone-webmap.env
      - hubzone-webmap-test.env
    entrypoint: ["/bin/bash"]
    environment:
    - HUBZONE_GOOGLE_API_KEY
    command: >
      -c "
        wget https://s3.amazonaws.com/sba-shared-services-lower-ci/public-files/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
        tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
        rm phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
        mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /bin && \
        rm -r phantomjs-2.1.1-linux-x86_64
        while ! nc -z postgres 5432;
        do
          echo waiting for postgres;
          sleep 1;
        done;
        echo Connected to postgres!;
        bundle exec rake db:create db:migrate &&
        bundle exec rspec spec;
      "
