files: ["**/*.js", "**/*.js.erb"] # No need to put app/assets/ or vendor/assets here
exclude_paths: ["vendor/assets/*", "**/helpers/"]
include_paths: ["app/views/", "spec/javascripts"]
options:
  boss:       true
  browser:    true
  curly:      true
  eqeqeq:     true
  eqnull:     true
  expr:       true
  immed:      true
  indent:     2
  latedef:    nofunc
  maxcomplexity: 5
  newcap:     true
  noarg:      true
  sub:        true
  trailing:   true
  undef:      true
  unused:     true
  globals:
    jQuery:   true
    "$":      true
    console:  true
    ActionCable: true
    App: true
    constructSLDXML: true
    google:   true
    hzBaseMapStyle: true
    hzWMSOverlays: true
    initMap: true
    jumpToLocation: true
    map: true
    mapGeoJson: true
    mapMarkers: true
    mapScope: true
    sidebar: true
    sinon: true
    updateAccordions: true
    updateMarkers: true
    spyOn: true
    expect: true
    describe: true
    beforeEach: true
    it: true
    xit: true
    triggerSidebar: true
