default: &defaults
  hubzone_map_version:
    major: 1
    minor: 7
    patch: 7
    pre_release:
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST') { 'http://localhost:3001' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST') { 'http://localhost:3001' } %>
  hubzone_api_version: 1
  hubzone_api_search_path: '/api/search'
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_API_HOST') { 'http://localhost:3002' } %>
  hubzone_api_report_path: '/report'
  hubzone_report_request_type: <%= ENV.fetch('HUBZONE_REPORT_REQUEST_TYPE') { 'window_open' } %>
  google_api_key: <%= ENV.fetch('HUBZONE_GOOGLE_API_KEY') { 'SetYourGoogleAPIKeyInYour.envFile' } %>
  google_analytics_tracking_id: <%= ENV.fetch('GOOGLE_ANALYTICS_TRACKING_ID') { 'UA-89111383-1' } %>
  hotjar_tracking_id: <%= ENV.fetch('HUBZONE_HOTJAR_TRACKING_ID') { '475456' } %>
  bind_window_events: true
  geom_wms_settings: &default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'http://localhost:8080/geoserver/gwc/service/wms?' } %>
    workspace: <%= ENV.fetch('HUBZONE_WMS_WORKSPACE') { 'hubzone' } %>
    srs: 4326
    wms_enabled: true


production:
  <<: *defaults
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST')       { 'https://maps.certify.sba.gov/' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST')       { 'https://maps.certify.sba.gov' } %>
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_HOST') { 'https://maps.certify.sba.gov' } %>
  hotjar_tracking_id: <%= ENV.fetch('HUBZONE_HOTJAR_TRACKING_ID') { '475424' } %>
  google_analytics_tracking_id: <%= ENV.fetch('GOOGLE_ANALYTICS_TRACKING_ID') { 'UA-19362636-24' } %>
  geom_wms_settings:
    <<: *default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'https://maps.certify.sba.gov/geoserver/gwc/service/wms?' } %>
    db: hzgeo_prd

staging:
  <<: *defaults
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST')       { 'https://maps.staging.certify.sba.gov/' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST')       { 'https://maps.staging.certify.sba.gov' } %>
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_HOST') { 'https://maps.staging.certify.sba.gov' } %>
  hotjar_tracking_id: <%= ENV.fetch('HUBZONE_HOTJAR_TRACKING_ID') { '435148' } %>
  geom_wms_settings:
    <<: *default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'https://maps.staging.certify.sba.gov/geoserver/gwc/service/wms?' } %>
    db: hzgeo_stg

training:
  <<: *defaults
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST')       { 'https://maps.training.certify.sba.gov/' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST')       { 'https://maps.training.certify.sba.gov' } %>
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_HOST') { 'https://maps.training.certify.sba.gov' } %>
  #TODO: Get Training ID for Hotjar
  hotjar_tracking_id: <%= ENV.fetch('HUBZONE_HOTJAR_TRACKING_ID') { '435148' } %>
  geom_wms_settings:
    <<: *default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'https://maps.training.certify.sba.gov/geoserver/gwc/service/wms?' } %>
    db: hzgeo_trn

qa:
  <<: *defaults
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST')       { 'https://hubzone.qa.sba-one.net/' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST')       { 'https://hubzone.qa.sba-one.net' } %>
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_HOST') { 'https://hubzone.qa.sba-one.net' } %>
  #TODO: Get QA ID for Hotjar
  hotjar_tracking_id: <%= ENV.fetch('HUBZONE_HOTJAR_TRACKING_ID') { '428263' } %>
  geom_wms_settings:
    <<: *default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'https://hubzone.qa.sba-one.net/geoserver/gwc/service/wms?' } %>
    db: hzgeo_qa

demo:
  <<: *defaults
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST')       { 'https://hz-demo.sba-one.net' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST')       { 'https://hz-demo.sba-one.net' } %>
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_HOST') { 'https://hz-demo.sba-one.net' } %>
  hotjar_tracking_id: <%= ENV.fetch('HUBZONE_HOTJAR_TRACKING_ID') { '428263' } %>
  geom_wms_settings:
    <<: *default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'https://hz-demo.sba-one.net/geoserver/gwc/service/wms?' } %>
    db: hzgeo_demo

dev:
  <<: *defaults
  hubzone_map_host: <%= ENV.fetch('HUBZONE_MAP_HOST')       { 'https://map.dev.sba-one.net' } %>
  hubzone_api_host: <%= ENV.fetch('HUBZONE_API_HOST')       { 'https://map.dev.sba-one.net' } %>
  hubzone_report_host: <%= ENV.fetch('HUBZONE_REPORT_HOST') { 'https://map.dev.sba-one.net' } %>
  geom_wms_settings:
    <<: *default_wms
    url_root: <%= ENV.fetch('HUBZONE_WMS_URL_ROOT') { 'https://map.dev.sba-one.net/geoserver/gwc/service/wms?' } %>
    db: hzgeo_dev

development:
  <<: *defaults
  geom_wms_settings:
    <<: *default_wms
    db: hzgeo_dev

test:
  <<: *defaults
  bind_window_events: false
  geom_wms_settings:
    <<: *default_wms
    db: why_are_you_hitting_the_WMS_server_in_test
