default: &defaults
  hubzone_api_host: <%= ENV["HUBZONE_API_HOST"] || "http://localhost:3001" %>
  google_api_key: <%= ENV["HUBZONE_GOOGLE_API_KEY"] ||
                      "need to set HUBZONE_GOOGLE_API_KEY in your environment!"
                      %>
  geomWFSSettings: &default_wfs
    urlRoot: <%= ENV["HUBZONE_WFS_URL_ROOT"] || "http://localhost:8080/geoserver/hubzone-test/ows?service=WFS" %>
    tableHighRes: hz_current
    tableLowRes: hz_current_lowres
    tableLowerRes: hz_current_lowerres
    tableLowestRes: hz_current_lowestres
    srs: 4326

production:
  <<: *defaults
  geomWFSSettings:
    <<: *default_wfs
    db: hzgeo_prd

development:
  <<: *defaults
  geomWFSSettings:
    <<: *default_wfs
    db: hzgeo_dev

test:
  <<: *defaults
  geomWFSSettings:
    <<: *default_wfs
    db: why_are_you_hitting_the_WFS_server_in_test
