default: &defaults
  google_api_key: <%= ENV["HUBZONE_GOOGLE_API_KEY"] ||
                      "need to set HUBZONE_GOOGLE_API_KEY in your environment!"
                      %>

production:
  <<: *defaults

development:
  <<: *defaults
  geomWFSSettings:
    urlRoot: 'http://localhost:8080/geoserver/hubzone-test/ows?service=WFS'
    db: 'hzgeo_dev'
    table: 'indian_lands'
    srs: '4326'

test:
  <<: *defaults
  geomWFSSettings:
    urlRoot: 'http://localhost:8080/geoserver/hubzone-test/ows?service=WFS'
    db: 'hubzone-test'
    table: 'indianlands_2014'
    srs: '4326'
