# global configuration for all jobs
name: Production
on:
  push:
    tags:
      - v*.*

# sets the default shell for all jobs
defaults:
  run:
    shell: bash

# permissions can be set globally for jobs
permissions:
  contents: read # contents is used for checking out code
  id-token: write

env:
  AWS_REGION: 'us-east-1'
  AWS_ECR_REGISTRY_ID: ''

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        id: ecr-login

      - name: ECR Build & Push
        uses: ./.github/actions/ecr
        with:
          registry: ${{ steps.ecr-login.outputs.registry }}
          repo: hubzone/hubzone-webmap
          tags: ${{ github.ref_name }}
          cache-from: ${{ github.ref_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v1
        id: ecr-login

      - name: Terraform Plan & Apply
        uses: ./.github/actions/terraform
        with:
          folder: ./terraform
          image: ${{ github.ref_name }}
          workspace: prod
