# global configuration for all jobs
name: Staging
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - rc-v*.*

# sets the default shell for all jobs
defaults:
  run:
    shell: bash

# permissions can be set globally for jobs
permissions:
  contents: read # contents is used for checking out code
  id-token: write

env:
  AWS_REGION: 'us-east-1'
  AWS_ECR_REGISTRY_ID: '222484291001'
  WORKSPACE: 'stg'

jobs:
  webmap:
    runs-on: ubuntu-latest
    environment: stg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ECR Login
        uses: aws-actions/amazon-ecr-login@v2
        id: ecr-login

      - name: ECR Build & Push
        uses: ./.github/actions/ecr
        with:
          registry: ${{ steps.ecr-login.outputs.registry }}
          repo: hubzone/hubzone-webmap
          tags: ${{ github.ref_name }} ${{ github.sha }}
          cache-from: ${{ github.ref_name }}

      - name: 'Install Terraform 1.9.5'
        uses: 'hashicorp/setup-terraform@v3'
        with:
          terraform_version: '1.9.5'

      - name: Terraform Plan & Apply
        uses: ./.github/actions/terraform
        with:
          folder: ./terraform
          image: ${{ github.sha }}
          workspace: ${{ env.WORKSPACE }}
