# global configuration for all jobs
name: Integration Tests
on: [push]

# sets the default shell for all jobs
defaults:
  run:
    shell: bash

# permissions can be set globally for jobs
permissions:
  contents: read # contents is used for checking out code
  id-token: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'

      - name: Install system dependencies
        run: bundle install

      # This appears to work. Have Certify team double check
      - name: rubocop
        run: rubocop

  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'

      - name: Install Phantom
        run: |
          wget https://s3.amazonaws.com/sba-shared-services-lower-ci/public-files/phantomjs-2.1.1-linux-x86_64.tar.bz2
          tar -xf phantomjs-2.1.1-linux-x86_64.tar.bz2
          rm phantomjs-2.1.1-linux-x86_64.tar.bz2
          sudo mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /bin/phantomjs
          sudo chmod 555 /bin/phantomjs
          rm -r phantomjs-2.1.1-linux-x86_64

      - name: Install system dependencies
        run: bundle install

      - name: Migrate Database
        run: bundle exec rake db:create db:migrate

      - name: Run R-Spec
        run: bundle exec rspec --format progress
        env:
          HUBZONE_MAP_DB_USER: postgres
          HUBZONE_MAP_DB_PASSWORD: postgres
          RAILS_ENV: test
          OPENSSL_CONF: /etc/ssl/
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
