# global configuration for all jobs
name: Integration Tests
on: [push]

# sets the default shell for all jobs
defaults:
  run:
    shell: bash

# permissions can be set globally for jobs
permissions:
  contents: read # contents is used for checking out code
  id-token: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'

      - name: Install system dependencies
        run: bundle install
      # This appears to work. Have Certify team double check
      - name: rubocop
        run: rubocop
